#!/bin/bash

do_nosetests() {
    $1 -v --with-coverage --cover-package=sos --cover-html
}

fail () {
    echo "$@: [FAILED]"
    exit 1
}

if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

echo "checking pep8 conformance"
pep8 . || fail pep8
echo "checking unit test suite (py2)"
do_nosetests nosetests || fail nosetests

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
